# Generated by Django 4.2.1 on 2023-05-21 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Серия')),
                ('inn', models.CharField(verbose_name='ИНН')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Coefficient_by_type_car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.FloatField(verbose_name='Коэффициент')),
            ],
            options={
                'verbose_name': 'Коэффициент по типу ТС',
                'verbose_name_plural': 'Коэффициенты по типу ТС',
            },
        ),
        migrations.CreateModel(
            name='Diagnostic_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.FloatField(verbose_name='Коэффициент')),
            ],
            options={
                'verbose_name': 'Наличие диагностической карты коэффициент',
                'verbose_name_plural': 'Наличие диагностической карты коэффициент',
            },
        ),
        migrations.CreateModel(
            name='Driver_coefficient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.FloatField(verbose_name='Коэффициент')),
            ],
            options={
                'verbose_name': 'Коэффициент по водителям',
                'verbose_name_plural': 'Коэффициент по водителям',
            },
        ),
        migrations.CreateModel(
            name='Executor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ф.И.О.')),
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
            },
        ),
        migrations.CreateModel(
            name='Natural_legal_person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=100, verbose_name='Лицо')),
            ],
            options={
                'verbose_name': 'Физ.лицо/Юр.лицо',
                'verbose_name_plural': 'Физ.лицо/Юр.лицо',
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Серия')),
            ],
            options={
                'verbose_name': 'Вид страхования',
                'verbose_name_plural': 'Виды страхования',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Субъект',
                'verbose_name_plural': 'Субъекты',
            },
        ),
        migrations.CreateModel(
            name='Osago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер бланка')),
                ('policy', models.CharField(max_length=16, verbose_name='Номер полиса')),
                ('car_model', models.CharField(max_length=50, verbose_name='Марка/модель ТС')),
                ('year', models.IntegerField(verbose_name='Год выпуска ТС')),
                ('engine_capacity', models.IntegerField(verbose_name='Объем двигателя, см3')),
                ('government_number', models.CharField(verbose_name='Гос.№ ТС')),
                ('VIN', models.CharField(max_length=20, verbose_name='VIN(VID)')),
                ('chassis_number', models.CharField(max_length=50, verbose_name='Номер кузова/шасси')),
                ('country', models.CharField(max_length=50, verbose_name='Страна регистрации ТС')),
                ('region', models.CharField(max_length=100, verbose_name='Регион')),
                ('date_of_birth_1', models.DateField(verbose_name='Дата рождения')),
                ('license_number_1', models.CharField(max_length=50, verbose_name='№ вод.удостоверения')),
                ('date_of_issue_drive_license_1', models.DateField(verbose_name='Дата выдачи водительского удостоверения')),
                ('date_of_birth_2', models.DateField(verbose_name='Дата рождения')),
                ('license_number_2', models.CharField(max_length=50, verbose_name='№ вод.удостоверения')),
                ('date_of_issue_drive_license_2', models.DateField(verbose_name='Дата выдачи водительского удостоверения')),
                ('date_of_birth_3', models.DateField(verbose_name='Дата рождения')),
                ('license_number_3', models.CharField(max_length=50, verbose_name='№ вод.удостоверения')),
                ('date_of_issue_drive_license_3', models.DateField(verbose_name='Дата выдачи водительского удостоверения')),
                ('date_of_birth_4', models.DateField(verbose_name='Дата рождения')),
                ('license_number_4', models.CharField(max_length=50, verbose_name='№ вод.удостоверения')),
                ('date_of_issue_drive_license_4', models.DateField(verbose_name='Дата выдачи водительского удостоверения')),
                ('policy_date_start', models.DateField(verbose_name='Дата начало действия полиса')),
                ('policy_date_expiration', models.DateField(verbose_name='Дата окончания действия полиса')),
                ('single_tariff', models.IntegerField(default=1680, verbose_name='Единый тариф')),
                ('insurance_start_date', models.DateField(verbose_name='Дата начало страхования')),
                ('insurance_start_end', models.DateField(verbose_name='Дата окончания страхования')),
                ('insurance_premium', models.FloatField(verbose_name='Страховая премия')),
                ('payment_state', models.CharField(default='Оплачено', max_length=100, verbose_name='Статус полаты')),
                ('coefficient_by_type_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.coefficient_by_type_car', verbose_name='Коэф.по типу ТС')),
                ('diagnostic_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.diagnostic_card', verbose_name='Наличие диагностической карты коэффициент')),
                ('driver_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.clients', verbose_name='Информация о водителе 1')),
                ('driver_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.clients', verbose_name='Информация о водителе 2')),
                ('driver_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.clients', verbose_name='Информация о водителе 3')),
                ('driver_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.clients', verbose_name='Информация о водителе 4')),
                ('driver_coefficient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.driver_coefficient', verbose_name='Коэффициент по водителям')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.executor', verbose_name='Юр.лицо/Физ.лицо')),
                ('insurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.clients', verbose_name='Страхователь')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.series', verbose_name='Серия')),
            ],
            options={
                'verbose_name': 'ОСАГО',
                'verbose_name_plural': 'ОСАГО',
            },
        ),
    ]
