# Generated by Django 4.2.1 on 2023-05-21 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_osago_chassis_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osago',
            name='chassis_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер кузова/шасси'),
        ),
        migrations.AlterField(
            model_name='osago',
            name='date_of_birth_1',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='osago',
            name='date_of_birth_2',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='osago',
            name='date_of_birth_3',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='osago',
            name='date_of_birth_4',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='osago',
            name='date_of_issue_drive_license_1',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи водительского удостоверения'),
        ),
        migrations.AlterField(
            model_name='osago',
            name='date_of_issue_drive_license_2',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи водительского удостоверения'),
        ),
        migrations.AlterField(
            model_name='osago',
            name='date_of_issue_drive_license_3',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи водительского удостоверения'),
        ),
        migrations.AlterField(
            model_name='osago',
            name='date_of_issue_drive_license_4',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи водительского удостоверения'),
        ),
        migrations.AlterField(
            model_name='osago',
            name='driver_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.clients', verbose_name='Информация о водителе 1'),
        ),
        migrations.AlterField(
            model_name='osago',
            name='driver_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.clients', verbose_name='Информация о водителе 2'),
        ),
        migrations.AlterField(
            model_name='osago',
            name='driver_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.clients', verbose_name='Информация о водителе 3'),
        ),
        migrations.AlterField(
            model_name='osago',
            name='driver_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.clients', verbose_name='Информация о водителе 4'),
        ),
        migrations.AlterField(
            model_name='osago',
            name='license_number_1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='№ вод.удостоверения'),
        ),
        migrations.AlterField(
            model_name='osago',
            name='license_number_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='№ вод.удостоверения'),
        ),
        migrations.AlterField(
            model_name='osago',
            name='license_number_3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='№ вод.удостоверения'),
        ),
        migrations.AlterField(
            model_name='osago',
            name='license_number_4',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='№ вод.удостоверения'),
        ),
        migrations.AlterField(
            model_name='osago',
            name='policy_date_expiration',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания действия полиса'),
        ),
        migrations.AlterField(
            model_name='osago',
            name='policy_date_start',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начало действия полиса'),
        ),
    ]
